version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '02:00'
      timezone: Europe/Berlin
    groups:
      dependencies:
        dependency-type: production
        exclude-patterns:
          - 'puppeteer*'
          - 'chrome-devtools-frontend'
        patterns:
          - '*'
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - 'puppeteer*'
        patterns:
          - '*'
      puppeteer:
        patterns:
          - 'puppeteer*'
      chrome-devtools-frontend:
        patterns:
          - 'chrome-devtools-frontend'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '04:00'
      timezone: Europe/Berlin
    groups:
      all:
        patterns:
          - '*'
